spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/autenticaciondb
    username: postgres
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080

logging:
  level:
    root: INFO
    co.com.autenticacion: DEBUG
